#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 16 20:16:08 2019

@author: alan
"""
import numpy
import cv2



I = [[8, 6, 2, 7], [6, 2, 4, 1], [5, 8, 5, 2], [3, 0, 3, 2]]
K = [[4, 3], [7, 2]]

answer=[[0,0,0],[0,0,0],[0,0,0]]

for i in range(0,3):
    for j in range(0,3):
        answer[i][j]=(I[1+i][1+j]*K[1][1]+I[0+i][1+j]*K[0][1]+I[1+i][0+j]*K[1][0]+I[0+i][0+j]*K[0][0])/(4+3+7+2)

VIDEO_NAME = 'VID_20171019_121723.mp4'    
PATH_TO_VIDEO = os.path.join('Video', VIDEO_NAME)

video = cv2.VideoCapture(PATH_TO_VIDEO)


(grabbed, frame) = video.read()
video.isOpened()
 ==============================================================================
 
 ==============================================================================
